# Generated by Django 4.2.18 on 2025-01-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_votings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='votings',
            name='type_of_voting',
            field=models.TextField(default='one'),
            preserve_default=False,
        ),
    ]
