# Generated by Django 4.2.18 on 2025-01-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено')], default='В ожидании', max_length=10, verbose_name='Статус'),
        ),
    ]
