# Generated by Django 5.1.5 on 2025-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
