# Generated by Django 5.1.5 on 2025-01-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_answer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='voting',
        ),
        migrations.RemoveField(
            model_name='user_answer',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='voting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='main.votings'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='voting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_orders', to='main.votings'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='User_answer',
        ),
    ]
