# Generated by Django 4.2.18 on 2025-01-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_user_answer_answer_remove_questions_voting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отказано')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
