# Generated by Django 4.2.18 on 2025-01-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отказано'), ('get_from_admin', 'Выдано админом')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
