# Generated by Django 5.1.5 on 2025-01-26 18:20

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_image_upload_path, verbose_name='Изображение предмета')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('completed', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус плана')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.supplier', verbose_name='Планируемый поставщик')),
            ],
            options={
                'verbose_name': 'Предмет инвентаря',
                'verbose_name_plural': 'Предметы инвентаря',
            },
        ),
    ]
