# Generated by Django 5.1.5 on 2025-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_item_image_alter_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Планируемый поставщик'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
