# Generated by Django 5.1.4 on 2025-01-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_item_supplier_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Имя предмета')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('used', 'Использованный'), ('broken', 'Сломанный')], default='new', max_length=20, verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отчета')),
            ],
            options={
                'verbose_name': 'Отчет об использовании',
                'verbose_name_plural': 'Отчеты об использовании',
            },
        ),
    ]
