# Generated by Django 5.1.4 on 2025-01-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_usagereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagereport',
            name='status',
            field=models.CharField(choices=[('one', 'Новый'), ('multi', 'Использованный'), ('end', 'Сломанный')], default='new', max_length=20, verbose_name='Состояние'),
        ),
    ]
